import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  AppBar,
  Button,
  Container,
  IconButton,
  Toolbar,
  Typography,
} from "@mui/material";
import EmailIcon from "@mui/icons-material/Email";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import GitHubIcon from "@mui/icons-material/GitHub";
import NameIcon from "../components/NameIcon";
import Emoji from "../components/Emoji";
import StyledMark from "../components/StyledMark";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col flex-1">
        <AppBar position="static" color="transparent">
          <Container maxWidth="xl" disableGutters>
            <Toolbar>
              <Link href="/">
                <a>
                  <NameIcon width="10rem" />
                </a>
              </Link>
              <div className="flex-1" />
              <Typography>
                Soon to work at{" "}
                <Link href="https://www.csgi.com/">
                  <a target="_blank">
                    <span className="text-red-500 font-bold">CSG</span>
                  </a>
                </Link>
              </Typography>
            </Toolbar>
          </Container>
        </AppBar>
        <Container
          maxWidth="md"
          classes={{
            root: "flex flex-col justify-center flex-1",
          }}
        >
          <div>
            <div className="text-4xl mb-4">
              <Emoji label="hand wave" symbol="👋" />
            </div>
            <Typography variant="h6" component="h2" className="font-thin">
              <span className="realistic-marker-highlight">Hello!</span>{" "}
              I&apos;m Nicolaus.
            </Typography>
            <Typography variant="h4" component="h1" className="font-thin">
              I am a final year computer science student in Australia with a
              keen interest in {/* TODO use theme */}
              <StyledMark colorHex="#3f50b5">
                software engineering
              </StyledMark>{" "}
              and
              <StyledMark colorHex="#3f50b5">web development</StyledMark>.
            </Typography>
            <div className="flex items-center">
              <Typography
                variant="h6"
                component="h2"
                className="font-thin mr-4"
              >
                Feel free to drop a message at
              </Typography>
              <Button
                variant="outlined"
                classes={{
                  root: "normal-case rounded-3xl",
                }}
              >
                <Typography variant="h5" component="h3">
                  nicolauscg@gmail.com
                </Typography>
              </Button>
            </div>
          </div>
        </Container>
      </main>
      <footer>
        <Container
          maxWidth="xl"
          classes={{
            root: "flex",
          }}
        >
          <div>
            <Typography variant="subtitle1" component="span">
              more elsewhere
            </Typography>
            <span className="ml-2">
              <Link href="mailto:nicolauscg@gmail.com">
                <a target="_blank">
                  <IconButton>
                    <EmailIcon />
                  </IconButton>
                </a>
              </Link>
              <Link href="https://www.linkedin.com/in/nicolauscg/">
                <a target="_blank">
                  <IconButton>
                    <LinkedInIcon />
                  </IconButton>
                </a>
              </Link>
              <Link href="https://github.com/nicolauscg">
                <a target="_blank">
                  <IconButton>
                    <GitHubIcon />
                  </IconButton>
                </a>
              </Link>
            </span>
          </div>
        </Container>
      </footer>
    </div>
  );
};

export default Home;
